[server]
# url: L5Proxy的WebSocket URL，建议使用WSS，也即是TLS加密连接
url = "wss://js.llwan.top/lFDBu0WTbYuClhPzXEFHyE3UWTicYU7dq9zhPLf5kqrDjOW2schlH2W5w8ZxQBV8"
# UUID: 账户的唯一ID，必须提供，否则无法登录L5Proxy服务器
uuid = "8870f4a1-063f-43a4-bac2-679a443b3d08"
# endpoint：用于标志本台机器，除非需要从L5Proxy反向代理端口，否则不需要填写
endpoint = "8870f4a1-063f-43a4-bac2-679a443b3d08"
# loglevl: 日志级别，可以不填写，默认是INFO级别
loglevel = "info"

[tunnel]
# count: WebSocket隧道数量，默认是3，一般不用填写,建议使用默认值即可
count = 1
# cap: 单个隧道运行同时并发的请求数量，默认是200,建议使用默认值即可
cap = 100

[bypass]
enabled = true
whitelist = "https://js.llwan.top/lFDBu0WTbYuClhPzXEFHyE3UWTicYU7dq9zhPLf5kqrDjOW2schlH2W5w8ZxQBV8/whitelist"

[tun]
enabled = false
mtu = 1500
dev = "tun0xy"
bypass = true
nshint = "8.8.8.8:53"

[http]
enabled = true
address = ":4051"
httpsaddr = ":4052"
certfile = "/home/abc/localhost.crt"
keyfile = "/home/abc/localhost.key"
bypass = true

[socks5]
enabled = true
address = ":4050"
bypass = true
