[server]
url = "wss://baobei.llwant.com/lFDBu0WTbYuClhPzXEFHyE3UWTicYU7dq9zhPLf5kqrDjOW2schlH2W5w8ZxQBV8"
uuid = "8870f4a1-063f-43a4-bac2-679a443b3d08"
endpoint = "8870f4a1-063f-43a4-bac2-679a443b3d08"

[tunnel]
count= 3
cap = 100

[log]
level = "info"
